import getUniqueKey from './getUniqueKey';
import getDateString from './getDateString';

function examplePoolsArray() {

    let example = [
        {
            meta: {
                key: getUniqueKey(),
                id: 1,
				status: [
					{
						index: 0,
						color: status0color,
						message: status0,
					}
				],
            },
            basics: {
                name: 'Pool 1',
                volume: '25000',
                structure: 'inground',
                location: 'outdoor',
                material: 'whiteplaster',
                sanitizer: 'chlorine',
                spa: true,
				cover: 'solid',
				swgmfg: 'Salt Water Co.',
				swgmodel: 'AXY-1800-S',
				blower: false,
				blowermfg: '',
				blowermodel: '',
				cleaner: true,
				cleanermfg: 'Polaris',
				cleanermodel: '380',
				boosterpump: true,
				boosterpumpmfg: 'Polaris',
				boosterpumpmodel: 'IHOIUH-6574-HGF897',
				waterfeatures: true,
				waterfeaturesdescription: 'Theres like, water and stuff popping off all over the place',
				infinityedge: true,
				lights: true,
				lightscount: 2,
				divingboard: true,
				ladders: true,
            },
			advanced: {
				plumbingdiameter: 2,
				skimmerscount: 2,
				skimmersmfg: 'Skimmer Tech.',
				skimmersmodel: 'DSFHTG-6574',
				skimmersbaskettype: 'AS',
				floorreturns: true,
				floorreturnscount: '4',
				automation: true,
				automationmfg: 'AutoCorp',
				automationmodel: 'Super Duper Premium Robot',
				uv: true,
				uvmfg: 'Bright Solutions',
				uvmodel: 'SUN-XL-9001',
			},
            pumps: [
                {
					key: getUniqueKey(),
                    index: 0,
                    name: 'Main Pump',
                    pumpmfg: 'pump co',
                    pumpmodel: 'abcdefg',
                    motormfg: 'motor co',
                    motormodel: 'hijklmn',
					hp: '1',
					voltage: '120',
					serial: '91245170923',
                }
            ],
            filters: [
                {
					key: getUniqueKey(),
                    index: 0,
                    name: 'Filter 1',
                    filtermfg: 'filter co',
                    filtermodel: 'opqrstuv',
                    filtertype: 'cartridge',
                    filtersize: '50',
					valve: 'mpv',
					serial: '12341241234',
                }
            ],
			heaters: [
				{
					key: getUniqueKey(),
					index: 0,
					name: 'Main Heater',
					fuel: 'propane',
					heatermfg: 'Warm Spot Llc.',
					heatermodel: 'UHB-785-UIOGBV',
					serial: 'SDFG681974SDFGSD147SD',
				}
			],
			water: [
				{
					index: 0,
					date: new Date().getTime(),
					datestr: getDateString(),
			        tc: 3,
			        fc: 2.5,
			        nacl: 2800,
			        tb: 0.5,
					bg: 1.0,
			        ph: 7.5,
			        ta: 150,
			        tds: 1000,
			        ch: 200,
			        ca: 17,
					fe: 1.0,
			        cu: 0.1,
			        phos: 1.1,
				},
				{
					index: 1,
					date: new Date().getTime(),
					datestr: getDateString(),
			        tc: 5,
			        fc: 3.5,
			        nacl: 2200,
			        tb: 1.5,
					bg: 2.0,
			        ph: 6.5,
			        ta: 125,
			        tds: 1200,
					ch: 180,
			        ca: 11,
			        fe: 2.0,
			        cu: 0.2,
			        phos: 2.2,
				}
			]
        },
        {
            meta: {
                key: getUniqueKey(),
                id: 2,
				status: [
					{
						index: 0,
						color: status1color,
						message: status1,
					}
				],
            },
            basics: {
                name: 'Pool 2',
                volume: '50000',
                structure: 'aboveground',
                location: 'indoor',
                material: 'vinyl',
                sanitizer: 'bromine',
                spa: true,
				cover: 'mesh',
				swgmfg: 'Salt Water Co.',
				swgmodel: 'AXY-1800-S',
				blower: true,
				blowermfg: 'Bubble Tech',
				blowermodel: 'Super Deluxe Bubble Wizard',
				cleaner: true,
				cleanermfg: 'Polaris',
				cleanermodel: '380',
				boosterpump: true,
				boosterpumpmfg: 'Polaris',
				boosterpumpmodel: 'IHOIUH-6574-HGF897',
				waterfeatures: true,
				waterfeaturesdescription: 'Theres like, water and stuff popping off all over the place',
				infinityedge: true,
				lights: true,
				lightscount: 2,
				divingboard: true,
				ladders: true,
            },
			advanced: {
				plumbingdiameter: 2,
				skimmerscount: 2,
				skimmersmfg: 'Skimmer Tech.',
				skimmersmodel: 'DSFHTG-6574',
				skimmersbaskettype: 'AS',
				floorreturns: true,
				floorreturnscount: '4',
				automation: true,
				automationmfg: 'AutoCorp',
				automationmodel: 'Super Duper Premium Robot',
				uv: true,
				uvmfg: 'Bright Solutions',
				uvmodel: 'SUN-XL-9001',
			},
            pumps: [
                {
                    key: getUniqueKey(),
					index: 0,
                    name: 'Pump 1',
                    pumpmfg: 'pump co',
                    pumpmodel: 'abcdefg',
                    motormfg: 'motor co',
                    motormodel: 'hijklmn',
					hp: '1',
					voltage: '120',
					serial: '91245170923',
                },
                {
                    key: getUniqueKey(),
					index: 1,
                    name: 'Pump 2',
                    pumpmfg: 'pump co',
                    pumpmodel: 'abcdefg',
                    motormfg: 'motor co',
                    motormodel: 'hijklmn',
					hp: '',
					voltage: '',
					serial: '',
                }
            ],
            filters: [
                {
                    key: getUniqueKey(),
					index: 0,
                    name: 'Filter 1',
                    filtermfg: 'filter co',
                    filtermodel: 'opqrstuv',
                    filtertype: 'de',
                    filtersize: '60',
					valve: 'mpv',
					serial: '12341241234',
                },
                {
                    key: getUniqueKey(),
					index: 1,
                    name: 'Filter 2',
                    filtermfg: 'filter co',
                    filtermodel: 'opqrstuv',
                    filtertype: 'de',
                    filtersize: '61',
					valve: '',
					serial: '',
                }
            ],
			heaters: [
				{
					key: getUniqueKey(),
					index: 0,
					name: 'Main Heater',
					fuel: 'propane',
					heatermfg: 'Warm Spot Llc.',
					heatermodel: 'UHB-785-UIOGBV',
					serial: 'SDFG681974SDFGSD147SD',
				}
			],
			water: [
				{
					index: 0,
					date: new Date().getTime(),
					datestr: getDateString(),
			        tc: 3,
			        fc: 2.5,
			        nacl: 2800,
			        tb: 0.5,
					bg: 3.0,
			        ph: 7.5,
			        ta: 150,
			        tds: 1000,
					ch: 200,
			        ca: 17,
					fe: 1.0,
			        cu: 0.1,
			        phos: 1.1,
				},
				{
					index: 1,
					date: new Date().getTime(),
					datestr: getDateString(),
			        tc: 5,
			        fc: 3.5,
			        nacl: 2200,
			        tb: 1.5,
					bg: 4.0,
			        ph: 6.5,
			        ta: 125,
			        tds: 1200,
			        ch: 180,
			        ca: 11,
			        fe: 2.0,
			        cu: 0.2,
			        phos: 2.2,
				},
				{
					index: 2,
					date: new Date().getTime(),
					datestr: getDateString(),
			        tc: 7,
			        fc: 4.5,
			        nacl: 1200,
			        tb: 2.5,
					bg: 5.0,
			        ph: 8.5,
			        ta: 190,
			        tds: 1100,
			        ch: 110,
			        ca: 10,
			        fe: 0.2,
			        cu: 2.0,
			        phos: 4.4,
				}
			]
        },
        {
            meta: {
                key: getUniqueKey(),
                id: 3,
				status: [
					{
						index: 0,
						color: status3color,
						message: status3,
					}
				],
            },
            basics: {
                name: 'Pool 3',
                volume: '25000',
                structure: 'inground',
                location: 'outdoor',
                material: 'whiteplaster',
                sanitizer: 'swg',
                spa: null,
				cover: 'solid',
				swgmfg: 'Salt Water Co.',
				swgmodel: 'AXY-1800-S',
				blower: null,
				blowermfg: '',
				blowermodel: '',
				cleaner: true,
				cleanermfg: 'Polaris',
				cleanermodel: '380',
				boosterpump: true,
				boosterpumpmfg: 'Polaris',
				boosterpumpmodel: 'IHOIUH-6574-HGF897',
				waterfeatures: true,
				waterfeaturesdescription: 'Theres like, water and stuff popping off all over the place',
				infinityedge: true,
				lights: true,
				lightscount: 2,
				divingboard: true,
				ladders: true,
            },
			advanced: {
				plumbingdiameter: 2,
				skimmerscount: 2,
				skimmersmfg: 'Skimmer Tech.',
				skimmersmodel: 'DSFHTG-6574',
				skimmersbaskettype: 'AS',
				floorreturns: true,
				floorreturnscount: '4',
				automation: true,
				automationmfg: 'AutoCorp',
				automationmodel: 'Super Duper Premium Robot',
				uv: true,
				uvmfg: 'Bright Solutions',
				uvmodel: 'SUN-XL-9001',
			},
            pumps: [
                {
					key: getUniqueKey(),
					index: 0,
                    name: 'Pump 1',
                    pumpmfg: 'pump co',
                    pumpmodel: 'abcdefg',
                    motormfg: 'motor co',
                    motormodel: 'hijklmn',
					hp: '1',
					voltage: '120',
					serial: '91245170923',
                }
            ],
            filters: [
                {
                    key: getUniqueKey(),
					index: 0,
                    name: 'Filter 1',
                    filtermfg: 'filter co',
                    filtermodel: 'opqrstuv',
                    filtertype: 'sand',
                    filtersize: '70',
					valve: 'mpv',
					serial: '12341241234',
                }
            ],
			heaters: [
				{
					key: getUniqueKey(),
					index: 0,
					name: 'Main Heater',
					fuel: 'propane',
					heatermfg: 'Warm Spot Llc.',
					heatermodel: 'UHB-785-UIOGBV',
					serial: 'SDFG681974SDFGSD147SD',
				}
			],
			water: [
				{
					index: 0,
					date: new Date().getTime(),
					datestr: getDateString(),
			        tc: 3,
			        fc: 2.5,
			        nacl: 2800,
			        tb: 0.5,
					bg: 6.0,
			        ph: 7.5,
			        ta: 150,
			        tds: 1000,
			        ch: 200,
			        ca: 17,
					fe: 1.0,
			        cu: 0.1,
			        phos: 1.1,
				},
				{
					index: 1,
					date: new Date().getTime(),
					datestr: getDateString(),
			        tc: 5,
			        fc: 3.5,
			        nacl: 2200,
			        tb: 1.5,
					bg: 7.0,
			        ph: 6.5,
			        ta: 125,
			        tds: 1200,
			        ch: 180,
			        ca: 11,
			        fe: 2.0,
			        cu: 0.2,
			        phos: 2.2,
				}
			]
        },
		{
            meta: {
                key: getUniqueKey(),
                id: 4,
				status: [
					{
						index: 0,
						color: status4color,
						message: status4,
					}
				],
            },
            basics: {
                name: 'Pool 4',
                volume: '25000',
                structure: 'inground',
                location: 'outdoor',
                material: 'whiteplaster',
                sanitizer: 'biguanide',
                spa: false,
				cover: 'mesh',
				swgmfg: 'Salt Water Co.',
				swgmodel: 'AXY-1800-S',
				blower: null,
				blowermfg: '',
				blowermodel: '',
				cleaner: true,
				cleanermfg: 'Polaris',
				cleanermodel: '380',
				boosterpump: true,
				boosterpumpmfg: 'Polaris',
				boosterpumpmodel: 'IHOIUH-6574-HGF897',
				waterfeatures: true,
				waterfeaturesdescription: 'Theres like, water and stuff popping off all over the place',
				infinityedge: true,
				lights: true,
				lightscount: 2,
				divingboard: true,
				ladders: true,
            },
			advanced: {
				plumbingdiameter: 2,
				skimmerscount: 2,
				skimmersmfg: 'Skimmer Tech.',
				skimmersmodel: 'DSFHTG-6574',
				skimmersbaskettype: 'AS',
				floorreturns: true,
				floorreturnscount: '4',
				automation: true,
				automationmfg: 'AutoCorp',
				automationmodel: 'Super Duper Premium Robot',
				uv: true,
				uvmfg: 'Bright Solutions',
				uvmodel: 'SUN-XL-9001',
			},
            pumps: [
                {
					key: getUniqueKey(),
					index: 0,
                    name: 'Pump 1',
                    pumpmfg: 'pump co',
                    pumpmodel: 'abcdefg',
                    motormfg: 'motor co',
                    motormodel: 'hijklmn',
					hp: '',
					voltage: '',
					serial: '',
                }
            ],
            filters: [
                {
                    key: getUniqueKey(),
					index: 0,
                    name: 'Filter 1',
                    filtermfg: 'filter co',
                    filtermodel: 'opqrstuv',
                    filtertype: 'sand',
                    filtersize: '70',
					valve: 'mpv',
					serial: '12341241234',
                }
            ],
			heaters: [
				{
					key: getUniqueKey(),
					index: 0,
					name: 'Main Heater',
					fuel: 'propane',
					heatermfg: 'Warm Spot Llc.',
					heatermodel: 'UHB-785-UIOGBV',
					serial: 'SDFG681974SDFGSD147SD',
				}
			],
			water: [
				{
					index: 0,
					date: new Date().getTime(),
					datestr: getDateString(),
			        tc: 3,
			        fc: 2.5,
			        nacl: 2800,
			        tb: 0.5,
					bg: 6.0,
			        ph: 7.5,
			        ta: 150,
			        tds: 1000,
			        ch: 200,
			        ca: 17,
					fe: 1.0,
			        cu: 0.1,
			        phos: 1.1,
				},
				{
					index: 1,
					date: new Date().getTime(),
					datestr: getDateString(),
			        tc: 5,
			        fc: 3.5,
			        nacl: 2200,
			        tb: 1.5,
					bg: 7.0,
			        ph: 6.5,
			        ta: 125,
			        tds: 1200,
			        ch: 180,
			        ca: 11,
			        fe: 2.0,
			        cu: 0.2,
			        phos: 2.2,
				}
			]
        }
    ];
    return example;
}

export default examplePoolsArray;
